config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  post 'bad_news' => 'users#bad_news'
  devise_for :users
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  authenticated :user do
    root :to => "pages#primary", as: :authenticated_root
  end
  root :to => "pages#primary"

  get 'users/:id/show' => 'users#show'
  post 'pusher/auth'
  resources :dishes
  resources :conversations, only: [:index, :show, :destroy]
  resources :messages, only: [:new, :create]

  get 'inbox' => 'users#inbox'
  get 'get_user_notif_count' => 'users#get_notif_count'
  post 'dishes/:id/soft_delete' => 'dishes#soft_delete'
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end
  post 'store_temporary_user_location' => 'users#temp_location'

  post 'create_multiple' => 'dishes#multicreate'
  get 'multicreate' => 'dishes#multicreate', as: 'multicreate_url'
  post 'delete_unfinished' => 'dishes#delete_unfinished'

  get '/charges/new' => 'charges#new'
  post '/charges/create' => 'charges#create'

  match '/users/:id/edit_latlong', to: 'users#edit_latlong', via: 'post'
  match '/users/:id/jsonify', to: 'users#jsonify', via: 'get'
  match '/users/get_ids', to: 'users#get_ids', via: 'get'
  get '/users/:id/dishes' => 'users#dishes'
  match '/oauth/connect', to: 'oauth#connect', via: 'get'
  match '/users/auth/instagram/callbacks', to: 'oauth#auth', via: 'get'

  get '/tos' => 'pages#tos'
  get '/privacy' => 'pages#privacy'
  get '/careers' => 'pages#careers'
  get '/primary' => 'pages#primary'

  get '/map' => 'pages#map'
  get '/map2' => 'pages#map2'
  get '/connect' => 'users#connect'
  post '/accepted_tos' => 'users#accepted_tos'
  post '/create_connected' => 'users#create_connected'

  get "/user_recent_media" => 'users#user_recent_media'
  get "/user_recent_media_single" => 'users#user_recent_media_single'
  get "/user_recent_media_single_prof" => 'users#user_recent_media_single_prof'
  post '/prof_pic_change' => 'users#prof_pic_change'

  post '/autocomplete' => 'search#search'

  get '/how-it-works' => 'pages#how_it_works'
  get '/getting-started' => 'pages#getting_started'

  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'

  post '/hooks/stripe' => 'hooks#stripe'

  post 'dishes/:id/order' => 'dishes#order', :as => "order_dish"

  get 'auth/facebook', as: "auth_provider"
  get 'cb', to: 'users#login'

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  post 'order_from_cart' => 'orders#order_from_cart'

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
 
  def new
  	@user = User.find_by(id: params[:user])
  end
 
  def create
    recipient = User.find(params[:user])
    recipient.notify("#{current_user.name} sent you a message!", "Filler");
    msg_body = params[:message][:body]
    msg_subj = params[:message][:subject]
    conversation = current_user.send_message(recipient, msg_body, msg_subj).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
    # naming convention for server-client channels is 'private-<%= id %>'
    channel = 'private-' + recipient.id.to_s
    # push notification to trigger the
    Pusher[channel].trigger('my_event', {
      message: '1 new message'
    })
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.name}</option>"
    end
    s.html_safe
  end
end

app/views/messages/new.html.erb
  <div class="panel panel-default" style="margin-top: 10px">
    <div class="panel-header container">
      <span style="text-align: center">
      <h4>Messaging <a href="/users/<%=@user.id%>/show"><%= User.find(@user.id).name %></a></h4>
       <h5>See <%= User.find(@user.id).name.split(" ")[0] %>'s <a href="/users/<%=@user.id%>/dishes">food</a></h5>  
      </span>
      
    </div>

    <div class="panel-body">
        <%= form_tag messages_path, method: :post do %>
          <div class="form-group">
            <%= label_tag 'message[subject]', 'Subject' %>
            <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
          </div>
         
          <div class="form-group">
            <%= label_tag 'message[body]', 'Message' %>
            <%= text_area_tag 'message[body]', nil, cols: 3, rows: 5, class: 'form-control', required: true %>
          </div>
         
          <% if !@user.nil? %>
            <%= hidden_field_tag(:user, "#{@user.id}") %>
          <% end %>
        <!--   <div class="form-group">
            <%= label_tag 'recipients', 'Choose recipients' %>
            <%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control chosen-it' %>
          </div> -->
         
          <%= submit_tag 'Send', class: 'btn btn-primary' %>
        <% end %>
    </div>
    
    <div class="panel-footer">
      <%= link_to 'Back', dishes_path %>
    </div>
  </div>