config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  post 'bad_news' => 'users#bad_news'
  devise_for :users
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  authenticated :user do
    root :to => "pages#primary", as: :authenticated_root
  end
  root :to => "pages#primary"

  get 'users/:id/show' => 'users#show'
  post 'pusher/auth'
  resources :dishes
  resources :conversations, only: [:index, :show, :destroy]
  resources :messages, only: [:new, :create]

  get 'inbox' => 'users#inbox'
  get 'get_user_notif_count' => 'users#get_notif_count'
  post 'dishes/:id/soft_delete' => 'dishes#soft_delete'
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end
  post 'store_temporary_user_location' => 'users#temp_location'

  post 'create_multiple' => 'dishes#multicreate'
  get 'multicreate' => 'dishes#multicreate', as: 'multicreate_url'
  post 'delete_unfinished' => 'dishes#delete_unfinished'

  get '/charges/new' => 'charges#new'
  post '/charges/create' => 'charges#create'

  match '/users/:id/edit_latlong', to: 'users#edit_latlong', via: 'post'
  match '/users/:id/jsonify', to: 'users#jsonify', via: 'get'
  match '/users/get_ids', to: 'users#get_ids', via: 'get'
  get '/users/:id/dishes' => 'users#dishes'
  match '/oauth/connect', to: 'oauth#connect', via: 'get'
  match '/users/auth/instagram/callbacks', to: 'oauth#auth', via: 'get'

  get '/tos' => 'pages#tos'
  get '/privacy' => 'pages#privacy'
  get '/careers' => 'pages#careers'
  get '/primary' => 'pages#primary'

  get '/map' => 'pages#map'
  get '/map2' => 'pages#map2'
  get '/connect' => 'users#connect'
  post '/accepted_tos' => 'users#accepted_tos'
  post '/create_connected' => 'users#create_connected'

  get "/user_recent_media" => 'users#user_recent_media'
  get "/user_recent_media_single" => 'users#user_recent_media_single'
  get "/user_recent_media_single_prof" => 'users#user_recent_media_single_prof'
  post '/prof_pic_change' => 'users#prof_pic_change'

  post '/autocomplete' => 'search#search'

  get '/how-it-works' => 'pages#how_it_works'
  get '/getting-started' => 'pages#getting_started'

  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'

  post '/hooks/stripe' => 'hooks#stripe'

  post 'dishes/:id/order' => 'dishes#order', :as => "order_dish"

  get 'auth/facebook', as: "auth_provider"
  get 'cb', to: 'users#login'

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  post 'order_from_cart' => 'orders#order_from_cart'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
	before_action :get_mailbox
	before_action :get_conversation, except: [:index, :empty_trash]
	before_action :get_box, only: [:index]
 
	def index
		if @box.eql? "inbox"
	    	@conversations = @mailbox.inbox
	  	elsif @box.eql? "sent"
	    	@conversations = @mailbox.sentbox
	  	else
			@conversations = @mailbox.trash
		end
		@conversations = @conversations.paginate(page: params[:page], per_page: 10)
		User.find(current_user.id).mailbox.notifications.all.each {|notification| notification.mark_as_read(User.find(current_user.id)) }
	 	# c = m.conversations
	 	# c.each {|convo|
	 	# 	ps = convo.participants
	 	# 	ps.each {|participant|
			# 	m.notifications.each {|notification| notification.mark_as_read(participant) }
	 	# 	}
	 	# }
	end

	def mark_as_read
	  @conversation.mark_as_read(current_user)
	  flash[:success] = 'The conversation was marked as read.'
	  redirect_to conversations_path
	end

	def empty_trash
	  @mailbox.trash.each do |conversation|
	    conversation.receipts_for(current_user).update_all(deleted: true)
	  end
	  flash[:success] = 'Your trash was cleaned!'
	  redirect_to conversations_path
	end

	 
	def show
	end

	def destroy
		@conversation.move_to_trash(current_user)
		flash[:success] = 'The conversation was moved to trash.'
		redirect_to conversations_path
	end

	def restore
		@conversation.untrash(current_user)
		flash[:success] = 'The conversation was restored.'
		redirect_to conversations_path
	end
 
 	def reply
  		current_user.reply_to_conversation(@conversation, params[:body])
  		@conversation.participants.each {|p|
  			channel = 'private-' + p.id.to_s
  			if p.id != current_user.id
		  		p.notify("#{current_user.name} sent you a message!", "xyz")
		  		Pusher[channel].trigger('my_event', {
					message: '1 new message'
				})
  			end
  		}
  		flash[:success] = 'Reply sent'
  		redirect_to conversation_path(@conversation)
  	end

	private
	 
	def get_box
	  if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
	    params[:box] = 'inbox'
	  end
	  @box = params[:box]
	end

 
  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
  	@conversation ||= @mailbox.conversations.find(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>
    <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
      	<% if conversation.is_unread?(current_user) %>
      		<%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                  class: 'btn btn-xs btn-info', method: :post %>
      <% end %>
    <% end %>
  </div>

  <p><%= render 'conversations/participants', conversation: conversation %></p>
  <p><%= conversation.last_message.body %>
      <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
  	<div class="parti" style="border:1px solid white; border-radius: 5px 5px 5px 5px; width: 120px; height: 120px; background-color: white;">
  	<p style="text-align: center;"> <%= participant.name %> </p>
  	<img src="<%= participant.prof_pic %>" height="75px" style="border-radius: 5px 5px 5px 5px; display: block; position: relative; margin-left: auto; margin-right: auto; bottom: 10px;">
  	</div>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="panel">
	<% page_header "Your Conversations" %>
	  
<!-- 	<p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p>
 -->

	<div class="row">
	  <div class="col-sm-3">
	    <ul class="nav nav-pills nav-stacked">
	      <%= mailbox_section 'inbox', @box %>
	      <%= mailbox_section 'sent', @box %>
	      <%= mailbox_section 'trash', @box %>
	    </ul>
	  </div>
	 
	  <div class="col-sm-9">
	    <% if @box == 'trash' %>
	    <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
	                   data: {confirm: 'Are you sure?'} %></p>
	  <% end %>

	    <ul class="list-group">
	      <%= render partial: 'conversations/conversation', collection: @conversations %>
	    </ul>
	 
	    <%= will_paginate %>
	  </div>
	</div>
</div>

app/views/conversations/show.html.erb
<% page_header "Conversation" %>
 
<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>
 
<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>
 
  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
            <img src="<%= message.sender.prof_pic %>" height="50px">
          </div>
 
          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>