config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  post 'bad_news' => 'users#bad_news'
  devise_for :users
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  authenticated :user do
    root :to => "pages#primary", as: :authenticated_root
  end
  root :to => "pages#primary"

  get 'users/:id/show' => 'users#show'
  post 'pusher/auth'
  resources :dishes
  resources :conversations, only: [:index, :show, :destroy]
  resources :messages, only: [:new, :create]

  get 'inbox' => 'users#inbox'
  get 'get_user_notif_count' => 'users#get_notif_count'
  post 'dishes/:id/soft_delete' => 'dishes#soft_delete'
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end
  post 'store_temporary_user_location' => 'users#temp_location'

  post 'create_multiple' => 'dishes#multicreate'
  get 'multicreate' => 'dishes#multicreate', as: 'multicreate_url'
  post 'delete_unfinished' => 'dishes#delete_unfinished'

  get '/charges/new' => 'charges#new'
  post '/charges/create' => 'charges#create'

  match '/users/:id/edit_latlong', to: 'users#edit_latlong', via: 'post'
  match '/users/:id/jsonify', to: 'users#jsonify', via: 'get'
  match '/users/get_ids', to: 'users#get_ids', via: 'get'
  get '/users/:id/dishes' => 'users#dishes'
  match '/oauth/connect', to: 'oauth#connect', via: 'get'
  match '/users/auth/instagram/callbacks', to: 'oauth#auth', via: 'get'

  get '/tos' => 'pages#tos'
  get '/privacy' => 'pages#privacy'
  get '/careers' => 'pages#careers'
  get '/primary' => 'pages#primary'

  get '/map' => 'pages#map'
  get '/map2' => 'pages#map2'
  get '/connect' => 'users#connect'
  post '/accepted_tos' => 'users#accepted_tos'
  post '/create_connected' => 'users#create_connected'

  get "/user_recent_media" => 'users#user_recent_media'
  get "/user_recent_media_single" => 'users#user_recent_media_single'
  get "/user_recent_media_single_prof" => 'users#user_recent_media_single_prof'
  post '/prof_pic_change' => 'users#prof_pic_change'

  post '/autocomplete' => 'search#search'

  get '/how-it-works' => 'pages#how_it_works'
  get '/getting-started' => 'pages#getting_started'

  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'

  post '/hooks/stripe' => 'hooks#stripe'

  post 'dishes/:id/order' => 'dishes#order', :as => "order_dish"

  get 'auth/facebook', as: "auth_provider"
  get 'cb', to: 'users#login'

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  post 'order_from_cart' => 'orders#order_from_cart'

end

app/models/user.rb
class User < ActiveRecord::Base
#	ac_field :name
  acts_as_messageable
  acts_as_mappable :default_units => :miles,
                 :default_formula => :sphere,
                 :distance_field_name => :distance,
                 :lat_column_name => :lat_f,
                 :lng_column_name => :long_f

  def self.current_user
    Thread.current[:current_user]
  end

  def self.current_user=(usr)
    Thread.current[:current_user] = usr
  end

  def mailboxer_email(object)
    return email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dishes

    has_many :sales,
           :class_name => "Order",
           :foreign_key => "seller_id"

    has_many :purchases,
            :class_name => "Order",
            :foreign_key => "buyer_id"

  def show
  	@user = User.find(params[:id])
  end

  def self.koala(auth, current_user_id)
    access_token = auth['token']
    facebook = Koala::Facebook::API.new(access_token)
    @obj = facebook.get_object("me?fields=name,picture,photos.limit(10).fields(id,picture)")
    @user = User.find(current_user_id)
    @user.update_attributes!(:fb_hd_profile_picture => 'https://graph.facebook.com/' + @obj["id"] + '/picture?type=large')
    @obj
  end

end	

app/controllers/users_controller.rb
class UsersController < ApplicationController
	respond_to :html, :json

	def connect
		respond_to do |format|
			format.js
		end
	end

	def bad_news
		puts "AMAZING_LIFE"
		puts params
	end

	def show
		@user = User.find(params[:id])
	end

	def inbox
	end

	def login
	    @user = User.koala(request.env['omniauth.auth']['credentials'], current_user.id)
	    @user = current_user
	    render 'users/show'
    end

    def get_notif_count
    	@notifs = User.find(current_user.id).mailbox.notifications(:read => false).length
    	puts @notifs
    	respond_to do |format|
    		format.js
    	end
    end

	def create_connected
		puts params
		@user = current_user
		account = Stripe::Account.retrieve(@user.connect_id)
		account.bank_account = params["token"]
		account.legal_entity.first_name = params["first_name"]
		account.legal_entity.last_name = params["last_name"]
		account.legal_entity.dob.year = params["dob1"].to_i
		account.legal_entity.dob.month = params["dob2"].to_i
		account.legal_entity.dob.day = params["dob3"].to_i
		account.legal_entity.type = "sole_prop"
		account.tos_acceptance.date = Time.now.to_i
		account.tos_acceptance.ip = request.remote_ip
		account.save
		@user.transfers_enabled = true
		@user.save

		respond_to do |format|
			format.js
		end
	end

	def accepted_tos
		@user = current_user
		puts @user.name
		@country = params["country"]
		@tos = params["tos"]

		if @user.connect_id.nil?
			connect = Stripe::Account.create({
			    :country => @country,
			    :managed => true,
			    :email => @user.email
		  	})
			@user.connect_id = connect["id"] 							# STRIPE CONNECT ID   -   acct_1679LjFP9ocVaMqO
			@user.secret_id = connect["keys"]["secret"] 				# STRIPE CONNECT SECRET ID   -   sk_test_MVrRKSz1xZM1g2Dwnzxf8x9E
			@user.publishable_id = connect["keys"]["publishable"]       # STRIPE CONNECT PUBLISHABLE ID   -   pk_test_FDc3ZDS37tv3UPF1Wqfyz2Nf
			@user.save
		end

		@connect_id = @user.connect_id
		@secret_key = @user.secret_id
		@publishable_key = @user.publishable_key

		respond_to do |format|
			format.js
		end
	
	end
	
	def edit_latlong
		respond_to do |format|   
			format.json {      # listen for json post request
				@user = User.find(params["id"])
				@user.update(lat: params["lat"], long: params["long"] )
				@user.update(lat_f: params["lat"].to_f, long_f: params["long"].to_f )
	        	@user.save
			    head :no_content # Send a no response to whoever sent the post.
			}
			format.html {
				# Normal form post request (form_for or w.e.)
			}
		end
	end

	def dishes
		@user = User.find(params["id"])
		@dishes = @user.dishes
    @order_item = current_order.order_items.new

		respond_to do |format|
	    	format.js
	    	format.html
	  	end
  end

  def temp_location
    puts "testing location"
    @location = params["location"]
    puts @location
    respond_to do |format|
      format.html
    end
  end

	def user_recent_media
		@client = Instagram.client(:access_token => session[:access_token])
        response = @client.user_recent_media
        @user = @client.user
        album = [].concat(response)
        max_id = response.pagination.next_max_id

        while !(max_id.to_s.empty?) do
            response = @client.user_recent_media(:max_id => max_id)
            max_id = response.pagination.next_max_id
            album.concat(response)
        end
        @album = album
        
        respond_to do |format|
        	format.js
        end
	end

	def user_recent_media_single
		@client = Instagram.client(:access_token => session[:access_token])
        response = @client.user_recent_media
        @user = @client.user
        album = [].concat(response)
        max_id = response.pagination.next_max_id

        while !(max_id.to_s.empty?) do
            response = @client.user_recent_media(:max_id => max_id)
            max_id = response.pagination.next_max_id
            album.concat(response)
        end
        @album = album
        
        respond_to do |format|
        	format.js
        end	
	end
	
	def prof_pic_change
		puts "Checking profile picture change and create"
		current_user.prof_pic = params['imageURL']
		if current_user.save 
			redirect_to root_path, notice: "Image uploaded!"
		else
			redirect_to root_path, notice: "Upload failed!"
		end
	end


	def user_recent_media_single_prof
		@client = Instagram.client(:access_token => session[:access_token])
        response = @client.user_recent_media
        @user = @client.user
        album = [].concat(response)
        max_id = response.pagination.next_max_id

        while !(max_id.to_s.empty?) do
            response = @client.user_recent_media(:max_id => max_id)
            max_id = response.pagination.next_max_id
            album.concat(response)
        end
        @album = album
        
        respond_to do |format|
        	format.js
        end	
	end


	def jsonify
		respond_to do |format|   
			format.json {      # listen for json post request
				@user = User.find(params["id"])
				json = Jsonify::Builder.new(:format => :pretty)
				json.person do
					json.name @user.name
					json.email @user.email
					json.home @user.home
					json.lat @user.lat
					json.long @user.long
					json.id @user.id
					json.prof_pic @user.prof_pic
				end
				render :json => json.compile!
			}
			format.html {
				# Normal form post request (form_for or w.e.)
			}
		end
	end

	def get_ids
		ids = []
		User.all.each {|u|
			ids.push(u.id)
		}
		respond_to do |format|
			format.json {
				render json: ids.to_json
			}
			format.html {

			}
		end
	end
	
    private
   		def user_params
      		params.require(:user).permit(:id, :name, :email, :phone_number, :home, :password, :lat, :long, :address_line_1, :address_line_2, :address_zip, :address_city, :address_state)
      	end
end

app/views/users/_dish_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= dish.name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
          <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency dish.price %></span></h4>
          <div class="input-group">
            <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
            <div class="input-group">
              <div class="input-group-btn">
                <%= f.hidden_field :dish_id, value: dish.id %>
                <%= f.submit "Add to Cart", class: "btn btn-primary" %>
              </div>
            </div>
            </form>
          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/users/_dish_row_table.html.erb
<%= form_for order_item, remote: true do |f| %>
    <!--<h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency dish.price %></span></h4>-->
    <div class="input-group">
      <!--<%= f.hidden_field :quantity, value: 1 %>-->

      <div class="input-group">
        <div class="input-group-btn">
          <%= f.hidden_field :dish_id, value: dish.id %>
          <td><%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %><%= f.submit "Add to Cart" %> </td> <!-- for Add to Card -->
        </div>
      </div>
      </form>
    </div>
<% end %>

app/views/users/_dishes.html.erb
<% if current_user %>
<div class="container" style="position: relative; padding-left: 0px; padding-right: 0px;">
  <div class="panel panel-default">
    <div class="panel-header container">
      <h4 style="text-align: center">Dishes by <a href="http://localhost:3000/users/<%= params["id"] %>/show"><%= User.find(params["id"]).name %></a> </h4>
    </div>

<style>
  table {
      border-padding: 10px;
  }

        th {
            text-align: center;
        }

</style>

    <div class="panel-body" style="max-height: 350px; width: 100%; overflow-y: scroll;">
      <table class="table-bordered">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Multiple</th>
            <th colspan="3">Quick</th>
          </tr>
        </thead>

        <tbody>
          <% @dishes.each do |dish| %>
            <tr>
              <% if dish.image_url != nil %>
                <td data-th="Image"><a href="https://www.trophus.com/dishes/<%= dish.id %>"><img height="75px" src='<%= dish.image_url %>'></a></td>
              <% else %>
                    <td>
                      <a href="https://www.trophus.com/dishes/<%= dish.id %>"><img height="75px" src='<%= dish.direct_image_url.gsub('https://',"http://") %>'></a>
                    </td>
              <% end %>
              <td><%= dish.name %></td>
              <td><%= dish.description %></td>
              <td>$<%= dish.price %></td>


              <%= render 'dish_row_table', dish: dish, order_item: @order_item %>
              <% if current_user.customer_id != nil %>
                  <td><%= link_to 'Order', order_dish_path(dish), method: :post, class: "btn-floating btn-large waves-effect waves-light blue" %></td>
              <% else %>
                  <td> <button class="red" onclick="addStripeInformation({'name':'<%= current_user.name %>','email':'<%= current_user.email %>'});" style="font-size: 15px; border-radius: 20px 20px 20px 20px; width: 70px; font-famiy: Helvetica Neue;">Add Card</button> </td>
              <% end %>


            </tr>

          <% end %>
        </tbody>

      </table>
    </div>

    <div class="panel-footer" style="text-align: center;">
      <%= link_to 'Back', root_path, method: :get, class: "btn btn-success"%>
    <% if @dishes.length > 0 %>
        <% if @dishes.first.user_id != current_user.id %>
          <%= link_to 'Send message', new_message_path(:user => User.find(@dishes.first.user_id)), class: 'btn btn-success'%>
        <% end %>
      <% end %>
            <%= link_to 'Check Out', '/cart', method: :get, class: "btn btn-success"%>

    </div>
  </div>
</div>

<% else %>
    <!--<script>-->
//      if (confirm('You must be signed in to view this page', "OK")) {
//        window.location.href = "https://www.trophus.com";
//      }
//      else {
//        window.location.href = "https://www.trophus.com";
//      }
//
//
    <!--</script>-->
<% end %>

app/views/users/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
          <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
          <div class="input-group">
            <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
                <div class="input-group">
                  <!--<p class="range-field">-->
                    <!--<input type="range" value="1" id="order_item_quantity" name="order_item[quantity]" min="1" max="5" />-->
                  <!--</p>-->
                  <div class="input-group-btn">
                    <%= f.hidden_field :product_id, value: product.id %>
                    <%= f.submit "Add to Cart", class: "btn btn-primary" %>
                  </div>
                </div>
              </form>


          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/users/_settings.html.haml
.panel.panel-primary
  .panel-body
    - if !current_user.nil?
      %h2 Stripe Account Management
      %p
        Account Type:
        %strong Managed

      - # the current account status, whether the
      - # account can make charges or can receive transfers
      %p
        .account-status
          Status:
          - charges = [ 'Charges', @user.stripe_account_status['charges_enabled'] ]
          - transfers = [ 'Transfers', @user.stripe_account_status['transfers_enabled'] ]
          %table
            - [ charges, transfers ].each do |text, yn|
              %tr
                %td
                  %span.label{ class: yn ? 'label-primary' : 'label-danger' }
                    %span.glyphicon{ class: yn ? 'glyphicon-ok' : 'glyphicon-remove' }
                    = text

      - # if we need more information from this user to keep
      - # their account in good standing
      - if @user.stripe_account_status['fields_needed'].any?
        %hr
        .needed
          = form_for @user, html: { class: 'form-horizontal' } do |f|
            %h3 Needed Information
            - if @user.stripe_account_status['due_by']
              %p
                Due by:
                %strong= Time.at( @user.stripe_account_status['due_by'] ).strftime("%Y-%m-%d")

            - if params[:debug]
              = debug @user.stripe_account_status['fields_needed']

            - manager = StripeManaged.new( current_user )
            %ul.list-group

              - # this account needs a bank account
              - if manager.needs? 'bank_account'
                %li.list-group-item#bank-account{ data: { publishable: @user.publishable_key } }
                  %script{ src: 'https://js.stripe.com/v2/' }
                  %h3 Bank Account
                  = hidden_field_tag :bank_account_token
                  .form-group
                    - countries = manager.supported_bank_account_countries
                    %label.control-label.col-xs-12.col-sm-3 Country:
                    .col-xs-12.col-sm-9
                      %select.form-control{ data: { stripe: 'country' } }
                        - countries.each do |country|
                          %option{ value: country[:code] }= country[:name]
                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Account Number:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', data: { stripe: 'account_number' } }
                  .form-group#bank-routing-container
                    %label.control-label.col-xs-12.col-sm-3 Routing Number:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', data: { stripe: 'routing_number' } }

              - # this account needs legal entity info
              - if manager.needs? 'legal_entity.'
                %li.list-group-item
                  %h3 Legal Entity
                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 First Name:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[first_name]', value: manager.legal_entity.first_name }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Last Name:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[last_name]', value: manager.legal_entity.last_name }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Date of Birth:
                    .col-xs-12.col-sm-9
                      - dob = manager.legal_entity.dob
                      - selected = Date.new( dob.year, dob.month, dob.day ) rescue nil
                      = date_select 'legal_entity', 'dob',
                          { selected: selected,
                            prompt: true,
                            start_year: 90.years.ago.year,
                            end_year: 13.years.ago.year },
                          { class: 'form-control' }

                  - if manager.needs? 'legal_entity.personal_id_number'
                    .form-group
                      %label.control-label.col-xs-12.col-sm-3 Personal ID Number:
                      .col-xs-12.col-sm-9
                        %input.form-control{ type: 'text', name: 'legal_entity[personal_id_number]' }
                  - elsif manager.needs? 'legal_entity.ssn_last_4'
                    .form-group
                      %label.control-label.col-xs-12.col-sm-3 SSN Last 4:
                      .col-xs-12.col-sm-9
                        %input.form-control{ type: 'text', name: 'legal_entity[ssn_last_4]' }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Address Line 1:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[address][line1]', value: manager.legal_entity.address.line1 }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 Address Line 2:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[address][line2]', value: manager.legal_entity.address.line2 }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 City:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[address][city]', value: manager.legal_entity.address.city }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 State/Province:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: 'legal_entity[address][state]', value: manager.legal_entity.address.state }

                  .form-group
                    %label.control-label.col-xs-12.col-sm-3 ZIP/Postal Code:
                    .col-xs-12.col-sm-9
                      %input.form-control{ type: 'text', name: "legal_entity[address][postal_code]", value: manager.legal_entity.address.postal_code }


            %br
            .buttons
              = f.submit 'Save Info', class: 'btn btn-lg btn-primary'

app/views/users/_show.html.erb
<div class = "container">

  <div class="panel panel-default" style="margin-top: 10%">
    <div class="panel-header container">
      <h5 style="text-align: center;"><%= @user.name %> </h5>
    </div>

    <div class="panel-body">

      <%= image_tag @user.prof_pic, style: "max-height: 200px; border-radius: 10px 10px 10px 10px;" %>

      </br>

      <div style="float: left;">
        <p> <%= @user.email %> </p>

        <% if User.find(@user.id).dishes.length > 0 %>
            <%= button_to "View dishes", "/users/" + @user.id.to_s + "/dishes", style: "margin-bottom: 5px;", class: "btn btn-success", method: :get %>
        <% else %>
            <p> <%= User.find(@user.id).name.split(" ")[0] %> hasn't added any dishes yet. </p>
        <% end %>

        <% if current_user %>
            <% if current_user.id == @user.id %>
                <% if session[:access_token].nil? %>
                    <a href="/oauth/connect">
                      <div class="userx" id="instagram-connect">Instagram Login</div>
                    </a>

                <% else %>
                    <% if current_user.prof_pic.nil? %>
    <span id="spannerbutton">
                                    <%= tag "input",
                                            { "type" => "button",
                                              class: "userx btn btn-success",
                                              "value" => "Add Profile Picture",
                                              "onclick" => "instaModalSingleProfilePic();"
                                            } %>
                                </span>
                    <% else %>
                                <span id="spannerbutton">
                                    <%= tag "input",
                                            { "type" => "button",
                                              class: "userx btn btn-success",
                                              "value" => "Change Profile Picture",
                                              "onclick" => "instaModalSingleProfilePic();"
                                            } %>
                                </span>
                    <% end %>
                <% end %>

            <% else %>

                <% unless current_user == @user %>
                    <%= link_to 'Send message', new_message_path(:user => @user.id), class: 'btn btn-default btn-sm' %>
                <% end %>

            <% end %>
        <% end %>
      </div>

    </div>

    <div class="panel-footer">
      <%= link_to 'Back', root_path %>
    </div>
  </div>
</div>

<div id="modalProfile" class="modal" aria-hidden="true" style="position: fixed;">
  <div class="modal-content"  style="overflow-y: auto; height: 400px;">
    <div class="picker"> <select class="image-picker show-html" id="insta_prof"></select> </div>
  </div>

  <div class="modal-footer">
    <button id="change-prof-pic" onclick="profChanger()" class="modal-action modal-close waves-effect waves-green btn-flat">SELECT</button>
    <button class="modal-action modal-close waves-effect waves-red btn-flat">CANCEL</button>
  </div>
</div>

app/views/users/accepted_tos.js.erb
var country_code = '<%= @country %>';
var tos_checked = '<%= @tos %>';

$('#modal2').openModal();

app/views/users/create_connected.html.erb
bootbox.alert("Bank account added!", function() {});

app/views/users/get_notif_count.js.erb
result = parseInt('<%= @notifs %>');
console.log(result);
var currNotifCount = $('.mdi-communication-forum').val();
if (result !== currNotifCount) {
	if (result === 0) {
		$('.mdi-communication-forum').empty();
	}
	else {
		$('.mdi-communication-forum').empty();
		$('.mdi-communication-forum').append(result);
	}
}

app/views/users/inbox.html.erb
  <div class="page-header">
    <h1><%= yield :page_header %></h1>
  </div>
  
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Synergy', root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Your Conversations', conversations_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</body>

app/views/users/login.html.erb
<p notice="Your personalized profile has been set up!"> </p>

<%= @user.name %>
<%= image_tag @user.fb_hd_profile_picture, style: "border-radius: 10px 10px 10px 10px;" %>

</br>

<%= @user.email %>

</br>


<%= @user.phone_number %>

app/views/users/show.html.erb
<div class = "container">

  <div class="panel panel-default" style="margin-top: 10%">
    <div class="panel-header container">
      <h5 style="text-align: center;"><%= @user.name %> </h5>
    </div>

    <div class="panel-body">

      <%= image_tag @user.prof_pic, style: "max-height: 200px; border-radius: 10px 10px 10px 10px;" %>

      </br>

      <div style="float: left;">
        <p> <%= @user.email %> </p>

        <% if User.find(@user.id).dishes.length > 0 %>
            <%= button_to "View dishes", "/users/" + @user.id.to_s + "/dishes", style: "margin-bottom: 5px;", class: "btn btn-success", method: :get %>
        <% else %>
            <p> <%= User.find(@user.id).name.split(" ")[0] %> hasn't added any dishes yet. </p>
        <% end %>

        <% if current_user %>
            <% if current_user.id == @user.id %>
                <% if session[:access_token].nil? %>
                    <a href="/oauth/connect">
                      <div class="userx" id="instagram-connect">Instagram Login</div>
                    </a>

                <% else %>
                    <% if current_user.prof_pic.nil? %>
    <span id="spannerbutton">
                                    <%= tag "input",
                                            { "type" => "button",
                                              class: "userx btn btn-success",
                                              "value" => "Add Profile Picture",
                                              "onclick" => "instaModalSingleProfilePic();"
                                            } %>
                                </span>
                    <% else %>
                                <span id="spannerbutton">
                                    <%= tag "input",
                                            { "type" => "button",
                                              class: "userx btn btn-success",
                                              "value" => "Change Profile Picture",
                                              "onclick" => "instaModalSingleProfilePic();"
                                            } %>
                                </span>
                    <% end %>
                <% end %>

            <% else %>

                <% unless current_user == @user %>
                    <%= link_to 'Send message', new_message_path(:user => @user.id), class: 'btn btn-default btn-sm' %>
                <% end %>

            <% end %>
        <% end %>
      </div>

    </div>

    <div class="panel-footer">
      <%= link_to 'Back', root_path %>
    </div>
  </div>
</div>

app/views/users/temp_location.html.erb
<%= render 'pages/map2' %>

app/views/users/user_recent_media_single.js.erb
// $(function() {
// 	<%	str = '' %>
// 	<% count = 0 %>
// 	var strings = []
// 	bootbox.confirm(" ", function(data) { 
// 		if (data === true) {
// 			imageURL = $("select").val();
// 			$('#instaject-outer').show();
// 			$('#instaject').empty();
// 			$('#instaject').append('<img height="100px" width="100px" src=' + '"' + imageURL + '"' + '>')
// 			$('#imageURL').val(imageURL);
// 		}
// 	});
	
// 	$(".modal-body").append('<div class="picker"> <select class="image-picker show-html"></select> </div>');
// 	<% @album.each_with_index do |media_item, index| %>
// 		$(".image-picker").append("<option data-img-src='" + '<%= media_item.images.thumbnail.url  %>' + "'value='<%= media_item.images.standard_resolution.url %>'>Image <%= index %></option>")
// 		<% if index > 50 then break end %>
// 	<% end %>

// 	$("select").imagepicker({
// 		// hide_select : false,
//   //       show_label  : false
// 	})
// });


$(function() {
	<% @album.each_with_index do |media_item, index| %>
		$(".image-picker").append("<option data-img-src='" + '<%= media_item.images.standard_resolution.url  %>' + "'value='<%= media_item.images.standard_resolution.url %>'>Image <%= index %></option>")
		<% if index > 50 then break end %>
	<% end %>

	$("select").imagepicker({
	})
});