config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'
  post 'bad_news' => 'users#bad_news'
  devise_for :users
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  authenticated :user do
    root :to => "pages#primary", as: :authenticated_root
  end
  root :to => "pages#primary"

  get 'users/:id/show' => 'users#show'
  post 'pusher/auth'
  resources :dishes
  resources :conversations, only: [:index, :show, :destroy]
  resources :messages, only: [:new, :create]

  get 'inbox' => 'users#inbox'
  get 'get_user_notif_count' => 'users#get_notif_count'
  post 'dishes/:id/soft_delete' => 'dishes#soft_delete'
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end
  post 'store_temporary_user_location' => 'users#temp_location'

  post 'create_multiple' => 'dishes#multicreate'
  get 'multicreate' => 'dishes#multicreate', as: 'multicreate_url'
  post 'delete_unfinished' => 'dishes#delete_unfinished'

  get '/charges/new' => 'charges#new'
  post '/charges/create' => 'charges#create'

  match '/users/:id/edit_latlong', to: 'users#edit_latlong', via: 'post'
  match '/users/:id/jsonify', to: 'users#jsonify', via: 'get'
  match '/users/get_ids', to: 'users#get_ids', via: 'get'
  get '/users/:id/dishes' => 'users#dishes'
  match '/oauth/connect', to: 'oauth#connect', via: 'get'
  match '/users/auth/instagram/callbacks', to: 'oauth#auth', via: 'get'

  get '/tos' => 'pages#tos'
  get '/privacy' => 'pages#privacy'
  get '/careers' => 'pages#careers'
  get '/primary' => 'pages#primary'

  get '/map' => 'pages#map'
  get '/map2' => 'pages#map2'
  get '/connect' => 'users#connect'
  post '/accepted_tos' => 'users#accepted_tos'
  post '/create_connected' => 'users#create_connected'

  get "/user_recent_media" => 'users#user_recent_media'
  get "/user_recent_media_single" => 'users#user_recent_media_single'
  get "/user_recent_media_single_prof" => 'users#user_recent_media_single_prof'
  post '/prof_pic_change' => 'users#prof_pic_change'

  post '/autocomplete' => 'search#search'

  get '/how-it-works' => 'pages#how_it_works'
  get '/getting-started' => 'pages#getting_started'

  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'

  post '/hooks/stripe' => 'hooks#stripe'

  post 'dishes/:id/order' => 'dishes#order', :as => "order_dish"

  get 'auth/facebook', as: "auth_provider"
  get 'cb', to: 'users#login'

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  post 'order_from_cart' => 'orders#order_from_cart'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	ac_field :name, search_fields: [:name, :description, :price]

  has_many :order_items

  default_scope { where(active: true) }


	belongs_to :chef,
		:class_name => "User",
		:primary_key => "user_id"

	has_attached_file :image, styles: { small: "100x100", med: "200x200", large: "500x500" }
	do_not_validate_attachment_file_type :image

	def self.picture_from_url(url)
    	self.image = URI.parse(url).open
  	end
end
Dish.import

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authenticate_user!
	respond_to :html, :json, :js

	def new
    @s3_direct_post = 
      S3_BUCKET.presigned_post(
        key: "uploads/#{SecureRandom.uuid}/${filename}", 
        success_action_status: 201, 
        acl: :public_read
      )
    @dish = Dish.new
	end

	def multicreate
		puts "testing multicreate"
		urls = params['urls']
	    @dishes = urls.map{ |url| 
	    	Dish.create(
	    		:image_url => url, 
	    		:user_id => current_user.id
	    	) 
	   	}
	    respond_to do |format|
	    	format.js
	    end
	end

	def delete_unfinished
		Dish.all.each { |dish|
			if dish.name.nil? 
				dish.delete
			end
		}
	end

	def show
		@dish = Dish.find(params["id"])
	end

	def index
		@dishes = current_user.dishes
	end

	def create
	    @dish = current_user.dishes.create(dish_params)
	    if current_user
	      if @dish.save()
	      	redirect_to dishes_path, notice: "Dish was created!"
	      else
	      	redirect_to dishes_path, notice: "Dish failed!"
	      	render :new
	      end
	    end
  	end

	def edit
		@dish = Dish.find(params["id"])
	end

	def destroy
		# puts "FRANKENSTEIN"
		# puts params["id"]
		@dish = Dish.find(params["id"])
		@dish.visible = false
		@dish.save()
	  redirect_to dishes_path, notice: 'Dish was successfully destroyed.'
	end

	def update
		@dish = Dish.find(params["id"])
	  	if @dish.update(dish_params)
	    	redirect_to dishes_path, notice: 'Dish was successfully updated.'
	    else
	      render :edit
	    end
	end

  # contains pricing logic for core business logic - shouldn't be in dishes controller
	def order
		@dish = Dish.find(params["id"])
		@amount = ((@dish.price + 0.3*@dish.price).ceil * 100).to_i
		charge = {
			:customer => current_user.customer_id, 
			:amount => ((@dish.price + 0.3*@dish.price).ceil * 100).to_i,
			:destination => User.find(@dish.user_id).connect_id,
			:application_fee => ((0.3*@dish.price).ceil * 100),
			:description => "[" + @dish.name + "]: " + "(" + @dish.description + ")",
			:currency => 'usd'
		}

		charge = Stripe::Charge.create(charge)

		num = User.find(@dish.user_id).phone_number
		str = ""
		if num != nil
			str = "Call them at #{num}. "
		end
		str << "Email them at #{User.find(@dish.user_id).email}"
		redirect_to @dish, notice: "(You were charged $#{@amount.fdiv 100}) #{User.find(@dish.user_id).name} is your point of contact! #{str}"
	end

	private
    def dish_params
    	if !params["image_url"].nil?
			params["image"] = Dish.picture_from_url(params["image_url"])
		end
    	params.require(:dish).permit(:name, :description, :price, :image, :image_url, :direct_image_url)
    end
end

app/views/dishes/_form.html.erb
<%= form_for(@dish, :html => { :multipart => true, :class => "directUpload" }) do |f| %>

<input type="hidden" name="dish[direct_image_url]" id="dish_direct_image_url">

<span id='hideAfter'>
<div id="place-image"></div>
<%= s3_uploader_form callback_url: 'bad_news', callback_param: "zoo",
                      class: "s3-uploader", 
                      id: "myS3Uploader" do %>
    <%= file_field_tag :file, multiple: false %>
<% end %>



  <%= f.hidden_field :direct_image_url %>

  <div class="form-group">
      <div id="instaject-outer" style="padding: 10px; display: none;"> <!-- style="display: none;"> -->
        <div id="instaject"></div>
      </div>

      <% if session[:access_token].nil? %>
        <a href="/oauth/connect">
            <button class="button btn btn-primary" id="instagram-connect">
                <i class="fa fa-instagram"></i>
                Connect to Instagram
            </button>
        </a>
      <% end %>


    <div class="file-field input-field">
      <input class="file-path form-control" type="text"/>
      <div class="btn">
        <span style="padding-right: 10px">File</span>
        <input id="dish_image" name="dish[image]" type="file" />
      </div>
    </div>
  </div>

  <div class="form-group">
    <span id="spannerbutton">
      <%= tag "input", { "type" => "button", class: "btn btn-success", "value" => "Instagram Upload", "onclick" => "instaModalSingle();" } %> 
    </span>
  </div>
</span>

  <%= f.hidden_field :image_url, :id => "imageURL" %>

  <div class="form-group"> 
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div> 
  
  <div class="form-group"> 
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group"> 
    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>
  </div> 

  <div class="actions"> 
    <%= f.submit :class => "btn btn-success" %>
  </div> 

<% end %>

app/views/dishes/_form_backup.html.erb
<%= form_for(@dish, :html => { :multipart => true, :class => "directUpload" }) do |f| %>

<input type="hidden" name="dish[direct_image_url]" id="dish_direct_image_url">

<span id='hideAfter'>
<div id="place-image"></div>
<%= s3_uploader_form callback_url: 'bad_news', callback_param: "zoo",
                      class: "s3-uploader", 
                      id: "myS3Uploader" do %>
    <%= file_field_tag :file, multiple: false %>
<% end %>



  <%= f.hidden_field :direct_image_url %>

  <div class="form-group">
      <div id="instaject-outer" style="padding: 10px; display: none;"> <!-- style="display: none;"> -->
        <div id="instaject"></div>
      </div>

      <% if session[:access_token].nil? %>
        <a href="/oauth/connect">
            <button class="button btn btn-primary" id="instagram-connect">
                <i class="fa fa-instagram"></i>
                Connect to Instagram
            </button>
        </a>
      <% end %>


    <div class="file-field input-field">
      <input class="file-path form-control" type="text"/>
      <div class="btn">
        <span style="padding-right: 10px">File</span>
        <input id="dish_image" name="dish[image]" type="file" />
      </div>
    </div>



  </div>

  <div class="form-group">



          <span id="spannerbutton">
        <%= tag "input", { "type" => "button", class: "btn btn-success", "value" => "Instagram Upload", "onclick" => "instaModalSingle();" } %> 
      </span>
  </div>
</span>

  <%= f.hidden_field :image_url, :id => "imageURL" %>

  <div class="form-group"> 
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div> 
  
  <div class="form-group"> 
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group"> 
    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>
  </div> 

  <div class="actions"> 
    <%= f.submit :class => "btn btn-success" %>
  </div> 

<% end %>

app/views/dishes/_form_direct.html.erb
<script id="template-upload" type="text/x-tmpl">
<div id="file-{%=o.unique_id%}" class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>




<div id="place-image"></div>
<!-- callback_param: "user[avatar_url]", 
                     callback_url: user -->
<%= s3_uploader_form class: "s3-uploader", 
                     id: "myS3Uploader" do %>
    <%= file_field_tag :file, multiple: false %>
<% end %>

<%= form_for(@dish) do |f| %>


  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <div id="instaject-outer" style="padding: 10px; display: none;"> <!-- style="display: none;"> -->
        <div id="instaject"></div>
      </div>

      <% if session[:access_token].nil? %>
        <a href="/oauth/connect">
            <button class="button btn btn-primary" id="instagram-connect">
                <i class="fa fa-instagram"></i>
                Connect to Instagram
            </button>
        </a>
      <% end %>
<!-- 

    <div class="file-field input-field">
      <input class="file-path form-control" type="text"/>
      <div class="btn">
        <span style="padding-right: 10px">File</span>
        <input id="dish_image" name="dish[image]" type="file" />
      </div>
    </div>
  </div> -->

  <div class="form-group">
    <span id="spannerbutton">
      <%= tag "input", { "type" => "button", class: "btn btn-success", "value" => "Instagram Upload", "onclick" => "instaModalSingle();" } %> 
    </span>
  </div>


  <%= f.hidden_field :direct_image_url %>

  <div class="form-group"> 
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div> 
  
  <div class="form-group"> 
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group"> 
    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>
  </div> 

  <div class="actions"> 
    <%= f.submit :class => "btn btn-success" %>
  </div> 
<% end %>

app/views/dishes/_multicreate.html.erb
  <div class="panel panel-default" style="margin-top: 10px">
    <div class="panel-header container">
      <h4>Create multiple dishes at once</h4>
    </div>

    <div class="panel-body">
      <%= render 'multicreate_form' %>
    </div>
    
    <div class="panel-footer">
      <%= link_to 'Back', dishes_path %>
    </div>
  </div>

app/views/dishes/_multicreate_form.html.erb
<%= form_for(dish, :html => { :multipart => true}) do |f| %> 
  <img height="100px" src="<%= dish.image_url %>">
  <%= f.hidden_field :image_url, :id => "imageURL" %>
  <div class="form-group"> 
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div> 
  
  <div class="form-group"> 
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group"> 
    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>
  </div> 

  <div class="actions"> 
    <%= f.submit :class => "btn btn-success", :style => "display: none" %>
  </div> 

<% end %>

app/views/dishes/edit.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-header container">
      <h1>Edit existing dish</h1>
    </div>

    <div class="panel-body">
      <%= render 'form' %>
    </div>
    
    <div class="panel-footer">
      <%= link_to 'Back', dishes_path %>
    </div>
  </div>
</div>

app/views/dishes/index.html.erb
<style>
.rwd-table {
  margin: 1em 0;
  min-width: 300px;
  border-collapse:collapse;
}

.rwd-table th {
  display: none;
}
.rwd-table td {
  display: block;
}
.rwd-table td:first-child {
  padding-top: .5em;
}
.rwd-table td:last-child {
  padding-bottom: .5em;
}
.rwd-table td:before {
  content: attr(data-th) "";
  width: 6.5em;
  display: inline-block;
}
@media (min-width: 480px) {
  .rwd-table td:before {
    display: none;
  }
}
.rwd-table th, .rwd-table td {
  text-align: left;
}
@media (min-width: 480px) {
  .rwd-table th, .rwd-table td {
    display: table-cell;
    padding: .25em .5em;
  }
  .rwd-table th:first-child, .rwd-table td:first-child {
    padding-left: 0;
  }
  .rwd-table th:last-child, .rwd-table td:last-child {
    padding-right: 0;
  }

}


h1 {
  font-weight: normal;
  letter-spacing: -1px;
}

.rwd-table {
/*  background: #34495E;
  color: #fff;*/
  border-radius: .4em;
  overflow: hidden;
}
.rwd-table tr {
/*  border-color: #46627f;*/
}
.rwd-table th, .rwd-table td {
  margin: .5em 1em;
}
@media (min-width: 480px) {
  .rwd-table th, .rwd-table td {
    padding: 1em !important;
  }
}
.rwd-table th, .rwd-table td:before {
/*  color: #dd5;*/
}

.table th, .table td, thead { 
     border-top: none !important; 
 }

thead {
  border-bottom: 0px;
}

 .adjusting-instagram {
  display: block;
  margin: 0 auto;
 }

 .dish_item {
    border:1px solid #26A69A;
    border-width: 1px;
 }


@media {
  .buttonic {
    display: inline-block;
    margin-bottom: 5px;
    margin-right: 5px;
  }
}

</style>


  <div class="panel panel-default" style="margin-top: 10px; width: 100%; height: 500px">
    <div class="panel-header">
      <h4 style="text-align: center">Listing your dishes</h4>

    <div class="adjusting-instagram">
      <div style="width: 30px"></div>
      <% if session[:access_token].nil? %>
          <button class="button btn btn-primary modal-trigger" onclick="window.location.href='/oauth/connect'" style="text-align: center; display: block; margin-left: auto; margin-right: auto;">
            Instagram Login
          </button>
      <% else %>
      <button class="button btn btn-primary modal-trigger" onclick="instaModal();" style="text-align: center; display: block; margin-left: auto; margin-right: auto;">
        Multicreate
      </button>
          <% end %>

<!-- <button class="button btn btn-primary" id="instagram-connect" style="margin: auto; margin-bottom: 10px; width: 140px; font-size: x-small;">
            <i class="fa fa-instagram" style="margin-right: 10px;"></i>
               SIGN IN
          </button> -->
    </div>
              <span id="spannerbutton"></span>
    
    </div>

    <div class="panel-body" style="height: 350px; overflow-y: scroll;">
      <table class="table rwd-table">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @dishes.each do |dish| %>
          <% if dish.visible != false %>
            <tr class="dish_item">
              <% if dish.image_url != nil %>
                <td data-th="Image"><a href="<%= ENV['APP_URL'] %>/dishes/<%= dish.id %>"><img height="75px" src='<%= dish.image_url %>'></a></td>
              <% else %>
                    <td>
                      <a href="<%= ENV['APP_URL'] %>/dishes/<%= dish.id %>"><img height="75px" src='<%= dish.direct_image_url.gsub('https://',"http://") %>'></a>
                    </td>
              <% end %>


              <td data-th="Name"><%= dish.name %></td>
              <td data-th="Description"><%= dish.description %></td>
              <td data-th="Price">$<%= dish.price %></td>

                <td class="btn-group" data-toggle="buttons">
            <span class="center-block">
            <button class="buttonic button btn"><a style="color: white;" href="<%= edit_dish_path(dish) %>">Edit</a></button>
            <button class="buttonic button btn"><%= link_to 'Delete', dish, :method => :delete, data: { confirm: 'Are you sure?' },  style: "color: white;"  %></button></span>
        </td>


<!-- <button class="buttonic button btn"><a style="color: white;" href="<%= edit_dish_path(dish) %>">Edit</a></button> <button class="buttonic button btn"><%= link_to 'Delete', dish, :method => :delete, data: { confirm: 'Are you sure?' },  style: "color: #e67e22;"  %></button> </td> -->
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>

app/views/dishes/multicreate.js.erb
$('#modal-multicreate').openModal();
<% @dishes.each {|dish| %>
	$("#modal-multicreate .modal-content").append("<%= j render(partial: 'dishes/multicreate_form', :locals => {:dish => dish }) %>");
<% } %>

app/views/dishes/new.html.erb
  <div class="panel panel-default" id="new_dish" style="margin-top: 10px">
    <div class="panel-header container">
      <h4>New dish</h4>
    </div>

    <div class="panel-body">
      <%= render 'form_direct' %>
    </div>
  </div>

app/views/dishes/order.html.erb
<p id="notice"></p>

<%= link_to 'Home', root_path %>

app/views/dishes/show.html.erb
<div class="panel panel-default" style="width: 100%">
  <div class="panel-heading">

  <style>
    #foodpic { 
      z-index: -100;
      max-height: 250; 
      border-radius:30px; 
      overflow: hidden; 
      box-shadow: 7px 7px 7px rgba(0,0,0,0.3);
      border-radius: 10px 10px 10px 10px;
    }


    #food_image img {
      border-radius: 10px 10px 10px 10px;  
    }

    #dish_data {
      margin-top:0px;
      padding-bottom: 15px;
    }
  

#desc {
  float: right;
}


  </style>

  <h4 id="dish_data">

      <span style="float:left; font-size: x-large;"> <%= @dish.name %></span></br>
      <span style="float:left; font-size: large;">  $<%= @dish.price %> </span>

      <% if current_user.customer_id != nil %>

      <div style="position: absolute; right: 0px; bottom: 5%">   <%= link_to 'Order', order_dish_path(@dish), method: :post, class: "btn-floating btn-large waves-effect waves-light blue", style: "font-size: 15px; bottom: 10px" %>
      </div>

      <% else %>

        <button class=" btn-large waves-effect waves-light red" onclick="addStripeInformation({'name':'<%= current_user.name %>','email':'<%= current_user.email %>'});" style="font-size: 10px; border-radius: 20px 20px 20px 20px; position: absolute; right: 0px; bottom: 5%">Add Card To Order</button>
      <% end %>


  </h4>

  </div>

    <div class="panel-body">

  <div id="food_image">

              <% if @dish.image_url != nil %>
                <img height="250px" src='<%= @dish.image_url %>'></td>
              <% else %>
                    <td>
                      <img height="250px" src='<%= @dish.direct_image_url.gsub('https://',"http://") %>'>
                    </td>
              <% end %>

        <div id="desc" style="text-align: center;"><h5><%= @dish.description %> </h5> </div>



          </div>


<h5 style="text-align: center;"></h5>

                

  </div>

<div class="panel-footer" style="min-height: 50px">
  <% if current_user.id == @dish.user_id %>
    <%= link_to 'Edit', edit_dish_path(@dish), class: "btn-floating btn-large waves-effect waves-light teal" %>
    <%= link_to 'Back', dishes_path, class: "btn-floating btn-large waves-effect waves-light teal" %>
  <% else %>
  <div style="float:right;"> Listed by <a style="font-size: small;" href='/users/<%= User.find(@dish.user_id).id %>/show'> <%= User.find(@dish.user_id).name %></a> </div>
  <% end %>
</div>

</div>